### ISSUE TITLE
What is the version of Tensorflow ans trfl?

### ISSUE THREAD

**Issue by LtECoD** [Dronie/D2D_A2C#5]
It seems that the last version of tensorflow doesn't work. Then what is the requirements of this repo, including tensorflow, trfl, and tensorflow_probability?

**Comment by Dronie** [comment]
My documentation of the versions used for each piece of software was quite poor so I'm not 100% sure of some of these.

Here are my best estimates however:
 - The version of Tensorflow used was 1.14.0
 - Not sure about tensorflow_probability, it could be anywhere from 0.7 - 0.11.0
 - TRFL should be fine with the most recent release (the majority of the code doesn't seem to have been updated since 2019)

Hope this helps
